
project_id = "wezlahokdkfhaveylnxo"

[functions.process-order]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false
