
-- Inserir produtos de exemplo
INSERT INTO public.products (nome, descricao, preco, preco_promocional, imagem_url, estoque, ativo) VALUES
('Extrato de Juba de Leão 30ml', 'Suplemento natural que fortalece o sistema imunológico do seu pet, promovendo mais energia, vitalidade e bem-estar geral. Rico em antioxidantes e compostos bioativos.', 89.90, 49.90, '/placeholder.svg', 100, true),
('Extrato de Juba de Leão 60ml', 'Versão econômica do nosso extrato premium. Ideal para pets de grande porte ou tratamentos prolongados. Mesmo produto, maior quantidade.', 159.90, 89.90, '/placeholder.svg', 50, true),
('Kit Juba de Leão + Suporte', 'Kit completo com 2 frascos de 30ml + suporte personalizado para administração. Perfeito para quem busca praticidade no dia a dia.', 199.90, 139.90, '/placeholder.svg', 25, true);

-- Inserir depoimentos de exemplo
INSERT INTO public.testimonials (nome, texto, aprovado, destaque, data) VALUES
('Maria Silva Santos', 'Incrível! O Max estava com baixa imunidade depois de uma cirurgia e o veterinário recomendou suplementação. Depois de 3 semanas usando o extrato de Juba de Leão, ele está muito mais disposto, brincalhão e saudável. O produto chegou super rápido e o atendimento foi excelente. Recomendo demais!', true, true, NOW() - INTERVAL '2 weeks'),
('João Carlos Lima', 'A Luna é uma cadela idosa de 12 anos e estava meio apática, dormindo muito. Com o Juba de Leão, em apenas 1 mês ela voltou a brincar, está mais alerta e até o pelo melhorou. Produto de qualidade excepcional e entrega super rápida. Vale cada centavo investido!', true, true, NOW() - INTERVAL '3 weeks'),
('Ana Costa Ferreira', 'Uso para meus dois cachorros há 2 meses. A diferença é visível! Eles estão mais animados, dispostos para passeios, com pelo mais bonito e brilhante, e não tiveram mais problemas de saúde. O produto é excelente e o preço justo. Já virei cliente fiel!', true, true, NOW() - INTERVAL '1 month'),
('Roberto Oliveira', 'Meu gato Mimi sempre foi muito medroso e estressado. Depois de usar o extrato por 6 semanas, ele está mais calmo, sociável e disposto. Até começou a brincar com outros gatos! Produto natural e seguro, recomendo para todos os tutores.', true, false, NOW() - INTERVAL '5 days'),
('Patricia Mendes', 'Produto maravilhoso! Minha cadela estava com problemas digestivos e baixa imunidade. Em 1 mês de uso, ela melhorou completamente. Está comendo bem, brincando e cheia de energia. O atendimento da empresa também é nota 10!', true, false, NOW() - INTERVAL '1 week'),
('Carlos Eduardo', 'Tenho 3 cães de diferentes idades e todos se beneficiaram com o Juba de Leão. Os mais jovens ficaram ainda mais ativos e os idosos ganharam mais disposição. Produto de altíssima qualidade, entrega rápida e embalagem impecável.', true, false, NOW() - INTERVAL '10 days');

-- Inserir FAQs de exemplo
INSERT INTO public.faqs (pergunta, resposta, ordem, ativo) VALUES
('O Extrato de Juba de Leão é seguro para meu pet?', 'Sim, nosso produto é 100% seguro e aprovado pelo MAPA (Ministério da Agricultura, Pecuária e Abastecimento). É desenvolvido especificamente para pets, seguindo rigorosos padrões de qualidade e segurança. Recomendamos sempre consultar um veterinário antes de iniciar qualquer suplementação, especialmente para pets com condições específicas de saúde.', 1, true),
('Em quanto tempo vou ver os resultados?', 'Os primeiros sinais de melhora geralmente aparecem entre 2-4 semanas de uso contínuo. Para resultados mais significativos e duradouros, recomendamos o uso por pelo menos 60-90 dias. Cada pet responde de forma diferente, mas a maioria dos tutores reporta melhorias na disposição, energia e bem-estar geral já nas primeiras semanas.', 2, true),
('Como devo administrar o produto?', 'A dosagem varia conforme o peso do pet: Para cães até 10kg: 0,5ml por dia. De 10-25kg: 1ml por dia. Acima de 25kg: 1,5ml por dia. Para gatos: 0,5ml por dia independente do peso. Pode ser misturado na ração úmida ou administrado diretamente na boca. Agite bem antes de usar e mantenha refrigerado após aberto.', 3, true),
('O produto tem garantia?', 'Sim! Oferecemos 30 dias de garantia total de satisfação. Se você não ficar completamente satisfeito com os resultados, devolvemos 100% do seu dinheiro, sem perguntas e sem burocracia. Nossa confiança na qualidade e eficácia do produto nos permite oferecer essa garantia completa.', 4, true),
('Posso dar para filhotes e pets idosos?', 'Sim! O produto é seguro para pets a partir de 3 meses de idade. Para filhotes muito pequenos (menos de 3 meses), recomendamos consultar um veterinário. Para pets idosos, o Juba de Leão é especialmente benéfico, ajudando a melhorar a qualidade de vida, disposição e função cognitiva.', 5, true),
('Tem contraindicações ou efeitos colaterais?', 'O Extrato de Juba de Leão é um produto natural sem contraindicações conhecidas. Em raros casos, alguns pets podem apresentar leve alteração no apetite nos primeiros dias de uso, que se normaliza rapidamente. Para pets gestantes, lactantes ou com doenças graves, sempre consulte um veterinário antes do uso.', 6, true),
('Como é feita a entrega?', 'Trabalhamos com frete grátis para todo o Brasil via Correios. O prazo de entrega varia de 3-7 dias úteis dependendo da região. Você recebe o código de rastreamento por email assim que o produto é despachado. Enviamos em embalagem discreta e segura para preservar a qualidade do produto.', 7, true),
('O produto precisa ser refrigerado?', 'Antes de abrir, o produto pode ser armazenado em temperatura ambiente, em local seco e arejado. Após aberto, deve ser mantido na geladeira e consumido em até 60 dias. Sempre agite bem antes de usar, pois é normal haver sedimentação natural dos compostos ativos.', 8, true);
